version: '2'
services:
    postgres:
        image: pos-atividade/db
        build: ./postgres
        container_name: postgres-db
        ports:
           - "5432:5432" 
    web:
        image: pos-atividade/app
        build: .
        container_name: app
        ports:
          - "8080:8080"
        links:
          - "postgres:postgres-db" 